name: test & release

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Test
      run: python3 -m unittest recent_projects_test
  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Build artifacts
      run: python3 build.py ${{ github.ref_name }}
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: '*.alfredworkflow'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
